// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using CatchException.Tagging.Tagging;
using System.Threading;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace CatchException.Tagging.Tagging.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITagLookupAppService), typeof(TagLookupClientProxy))]
public partial class TagLookupClientProxy : ClientProxyBase<ITagLookupAppService>, ITagLookupAppService
{
    public virtual async Task<TagData> FindByIdAsync(Guid id, CancellationToken cancellationToken)
    {
        return await RequestAsync<TagData>(nameof(FindByIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<List<TagData>> SearchAsync(string filter, int maxResultCount, CancellationToken cancellationToken)
    {
        return await RequestAsync<List<TagData>>(nameof(SearchAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), filter },
            { typeof(int), maxResultCount },
            { typeof(CancellationToken), cancellationToken }
        });
    }
}
