// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using CatchException.Tagging.Tagging;
using CatchException.Tagging.Tagging.Dtos;
using System.Collections.Generic;
using System.Threading;

// ReSharper disable once CheckNamespace
namespace CatchException.Tagging.Tagging.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITagAppService), typeof(TagsClientProxy))]
public partial class TagsClientProxy : ClientProxyBase<ITagAppService>, ITagAppService
{
    public virtual async Task<TagDto> CreateAsync(CreateTagDto input)
    {
        return await RequestAsync<TagDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateTagDto), input }
        });
    }

    public virtual async Task<List<TagDto>> GetListAsync(GetTagListInput input, CancellationToken cancellationToken)
    {
        return await RequestAsync<List<TagDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetTagListInput), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }
}
